tooltips:
  # Basic buttons
  button_attack: "This button makes unit attack other unit
                  <br><p color=green>(0/2/0)</p>"
  button_hpsacrificesu: "Sacrifices 2 HP to add 3 SU\n(2/0/0)"
  button_move: "Moves unit<br><p color=green>(0/1/0)</p>"

  # Building buttons
  button_building_scrap: "Destroys building"

  # Unit specific buttons
  button_artillery_shelling: "Shells 3x3 area (50% chance to hit one tile) <br><p color=green>(0/5/0)</p>"
  button_fortification_load_infantry: "Loads infantry unit into fortification"

  button_motorize: "Transforms a unit into a Motorized Unit which can be<br>transformed back into it's original form<br><p color=green>(0/3/0)</p>"
  button_motorized_unit_other_demotorize: "Transforms a unit back into it's original form"
  button_recover: "Gives unit 2 HP<br><p color=green>(0/3/0)</p>"

  button_repair: "Repairs mechanized units<br><p color=green>(0/4/0)</p>"
  button_engineer_unit_build_menu_build_military_tent: "Builds Base<br>Construction Time: 1<br><p color=green>(0/0/3)</p>"
  button_engineer_unit_build_menu_build_tank_factory: "Builds Tank Factory<br>Construction Time: 2<br><p color=green>(0/0/3)</p>" # 3
  button_engineer_unit_build_menu_build_supply_station: "Builds Supply Station<br>Construction Time: 2<br><p color=green>(0/0/3)</p>" # 4
  button_engineer_unit_build_menu_build_fortification: "Builds Fortification<br>Construction Time: 2<br><p color=green>(0/0/3)</p>"
  button_engineer_unit_build_menu_build_radar: "Builds Radar<br>Construction Time: 1<br><p color=green>(0/0/2)</p>"
  button_engineer_unit_build_menu_build_factory: "Builds Factory <br>Factory increases your income per turn by 1<br>Construction Time: 2<br><p color=green>(0/0/3)</p>"

  button_engineer_unit_build_menu: "Enters build menu"
  button_engineer_unit_build_menu_exit: "Exits build menu"

  button_train_infantry: "Trains Infantry<br>Production time: 1<br><p color=green>(0/0/1)</p>"
  button_train_machine_gunner: "Trains Heavy Infantry<br>Production time: 1<br><p color=green>(0/0/3)</p>"
  button_train_artillery: 'Trains Artillery<br>Production time: 1<br><p color=green>(0/0/2)</p>'
  button_train_anti_tank: 'Trains Anti-Tank<br>Production time: 2<br><p color=green>(0/0/3)</p>'
  button_train_engineer_unit: 'Trains Engineer<br>Production time: 1<br><p color=green>(0/0/1)</p>'
  button_train_motorized_unit_unit: 'Trains Supply Truck<br>Production time: 1<br><p color=green>(0/0/2)</p>'

  button_set_deployment_point: "Sets unit deployment point"
  button_cancel_train: "Cancels training of a unit without returning it's cost"

  button_train_light_tank: 'Trains Light Tank<br>Production time: 2<br><p color=green>(0/0/3)</p>'
  button_train_tankette: 'Trains Tankette<br>Production time: 2<br><p color=green>(0/0/2)</p>'
  button_train_heavy_tank: 'Trains Heavy Tank<br>Production time: 2<br><p color=green>(0/0/3)</p>'

  # For old server
  button_produce_light_tank: 'Trains Light Tank<br>Production time: 4<br><p color=green>(0/0/6)</p>'
  button_produce_heavy_tank: 'Trains Heavy Tank<br>Production time: 4<br><p color=green>(0/0/7)</p>'

  # Machine Gunner
  button_machine_gunner_defensive: 'Sets Heavy Infantry on defensive'
  button_machine_gunner_offensive: 'Sets Heavy Infantry on offensive'



