tooltips:
  # Basic buttons
  button_attack: "<html>This button makes unit attack other unit
                  <br><p color=green>(0/2/0)</p></html>"
  button_hpsacrificesu: "Sacrifices HP to add 2 SU\n(1/0/0)"
  button_move: "<html>Moves unit<br><p color=green>(0/1/0)</p></html>"

  # Building buttons
  button_building_scrap: "Destroys building"

  # Unit specific buttons
  button_artillery_shelling: "<html>Shells 3x3 area (50% chance to hit one tile) <br><p color=green>(0/5/0)</p></html>"

  button_repair: "<html>Repairs mechanized units<br><p color=green>(0/4/0)</p></html>"
  button_engineer_unit_build_menu_build_military_tent: "<html>Constructs Base<br><p color=green>(0/0/2)</p></html>"
  button_engineer_unit_build_menu_build_tank_factory: "<html>Constructs Tank Factory<br><p color=green>(0/0/3)</p></html>" # 3
  button_engineer_unit_build_menu_build_supply_station: "<html>Constructs Supply Station which increases your income per turn by 1<br><p color=green>(0/0/4)</p></html>" # 4

  button_engineer_unit_build_menu: "Enters build menu"
  button_engineer_unit_build_menu_exit: "Exits build menu"

  button_train_infantry: "<html>Trains Infantry<br>Production time: 2<br><p color=green>(0/0/2)</p></html>"
  button_train_artillery: '<html>Trains Artillery<br>Production time: 3<br><p color=green>(0/0/3)</p></html>'
  button_train_anti_tank: '<html>Trains Anti-Tank<br>Production time: 5<br><p color=green>(0/0/5)</p></html>'
  button_train_engineer_unit: '<html>Trains Engineer<br>Production time: 1<br><p color=green>(0/0/1)</p></html>'
  button_train_motorized_unit_unit: '<html>Trains Motorized Unit<br>Production time: 2<br><p color=green>(0/0/2)</p></html>'

  button_set_deployment_point: "Sets unit deployment point"
  button_cancel_train: "Cancels training of a unit without returning it's cost"

  button_train_light_tank: '<html>Trains Light Tank<br>Production time: 4<br><p color=green>(0/0/6)</p></html>'
  button_train_heavy_tank: '<html>Trains Heavy Tank<br>Production time: 4<br><p color=green>(0/0/7)</p></html>'

  # For old server
  button_produce_light_tank: '<html>Trains Light Tank<br>Production time: 4<br><p color=green>(0/0/6)</p></html>'
  button_produce_heavy_tank: '<html>Trains Heavy Tank<br>Production time: 4<br><p color=green>(0/0/7)</p></html>'



