properties:
  atk: "ATK"
  df: "DF"
  hp: "HP"
  su: "SU"
  ar: "Armor"
  atk_ar_1: "ATK (vs Armor: 1)"
  atk_ar_2: "ATK (vs Armor: 2)"
  ended_turn: "Has ended it's turn"
  construction_time: "Construction time"
  et: "ET"
  isAir: "Flight"